server:
  port: 8787
spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  application:
    qos-enable: false #禁用qos运维端口
  cloud:
    subscribed-services: provider  #订阅的服务列表，默认订阅所有服务
  registry:
    address: spring-cloud://localhost #挂载到SpringCloud注册中心

