server:
  port: 8787
spring:
  application:
    name: consumer
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource: #由Nacos管理sentinel规则，使其规则持久化,保证重启时不会丢失sentinel规则
        flow: #限流规则持久化 （flow：自定义数据源名称）
          nacos:
            rule-type: flow
            group-id: SENTINEL_GROUP
            data-id: ${spring.application.name}-sentinel-flow
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
        degrade: #降级规则持久化 （degrade：自定义数据源名称）
          nacos:
            rule-type: degrade
            group-id: SENTINEL_GROUP
            data-id: ${spring.application.name}-sentinel-degrade
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  application:
    qos-enable: false #禁用qos运维端口
  cloud:
    subscribed-services: provider  #订阅的服务列表，默认订阅所有服务
  registry:
    address: spring-cloud://localhost #挂载到SpringCloud注册中心

