server:
  port: 8081

spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  # 协议
  protocol:
    port: -1
    name: dubbo
  # 服务扫描
  scan:
    base-packages: com.example.provider.dubbo
  # qos端口
  application:
    qos-enable: true
    qos-port: 22222
  # 注册中心
  registry:
    address: spring-cloud://localhost
    port: 8848
  cloud:
    subscribed-services: /